project_name: cosi-tool

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh

builds:
    -
        main: main.go

        binary: bin/cosi

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris

        goarch:
            - amd64

        ignore:
            -
                goarch: 386

        ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archives:
    - id: default
      name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

      format: tar.gz

      replacements:
          amd64: x86_64

      format_overrides:
          -
              goos: windows
              format: zip

      files:
          - LICENSE
          - README.md
          - CHANGELOG.md
          - etc/example-reg-conf.toml

release:
    github:
        owner: circonus-labs
        name: cosi-tool

    prerelease: false
    draft: false
    name_template: "{{.ProjectName}}-v{{.Version}}"

changelog:
    filters:
        exclude:
            - '^doc:'
            - typo
    sort: asc

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
