[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  # v1.0.0 is out of date and owner is not maintaining
  # version = "1.0.0"
  branch = "master"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"
