// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package worksheets

import (
	"github.com/circonus-labs/circonus-gometrics/api"
	"sync"
)

var (
	lockCircAPIMockCreateWorksheet      sync.RWMutex
	lockCircAPIMockDeleteWorksheetByCID sync.RWMutex
	lockCircAPIMockFetchWorksheet       sync.RWMutex
	lockCircAPIMockSearchWorksheets     sync.RWMutex
	lockCircAPIMockUpdateWorksheet      sync.RWMutex
)

// CircAPIMock is a mock implementation of CircAPI.
//
//     func TestSomethingThatUsesCircAPI(t *testing.T) {
//
//         // make and configure a mocked CircAPI
//         mockedCircAPI := &CircAPIMock{
//             CreateWorksheetFunc: func(cfg *api.Worksheet) (*api.Worksheet, error) {
// 	               panic("TODO: mock out the CreateWorksheet method")
//             },
//             DeleteWorksheetByCIDFunc: func(cid api.CIDType) (bool, error) {
// 	               panic("TODO: mock out the DeleteWorksheetByCID method")
//             },
//             FetchWorksheetFunc: func(cid api.CIDType) (*api.Worksheet, error) {
// 	               panic("TODO: mock out the FetchWorksheet method")
//             },
//             SearchWorksheetsFunc: func(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Worksheet, error) {
// 	               panic("TODO: mock out the SearchWorksheets method")
//             },
//             UpdateWorksheetFunc: func(cfg *api.Worksheet) (*api.Worksheet, error) {
// 	               panic("TODO: mock out the UpdateWorksheet method")
//             },
//         }
//
//         // TODO: use mockedCircAPI in code that requires CircAPI
//         //       and then make assertions.
//
//     }
type CircAPIMock struct {
	// CreateWorksheetFunc mocks the CreateWorksheet method.
	CreateWorksheetFunc func(cfg *api.Worksheet) (*api.Worksheet, error)

	// DeleteWorksheetByCIDFunc mocks the DeleteWorksheetByCID method.
	DeleteWorksheetByCIDFunc func(cid api.CIDType) (bool, error)

	// FetchWorksheetFunc mocks the FetchWorksheet method.
	FetchWorksheetFunc func(cid api.CIDType) (*api.Worksheet, error)

	// SearchWorksheetsFunc mocks the SearchWorksheets method.
	SearchWorksheetsFunc func(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Worksheet, error)

	// UpdateWorksheetFunc mocks the UpdateWorksheet method.
	UpdateWorksheetFunc func(cfg *api.Worksheet) (*api.Worksheet, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateWorksheet holds details about calls to the CreateWorksheet method.
		CreateWorksheet []struct {
			// Cfg is the cfg argument value.
			Cfg *api.Worksheet
		}
		// DeleteWorksheetByCID holds details about calls to the DeleteWorksheetByCID method.
		DeleteWorksheetByCID []struct {
			// Cid is the cid argument value.
			Cid api.CIDType
		}
		// FetchWorksheet holds details about calls to the FetchWorksheet method.
		FetchWorksheet []struct {
			// Cid is the cid argument value.
			Cid api.CIDType
		}
		// SearchWorksheets holds details about calls to the SearchWorksheets method.
		SearchWorksheets []struct {
			// SearchCriteria is the searchCriteria argument value.
			SearchCriteria *api.SearchQueryType
			// FilterCriteria is the filterCriteria argument value.
			FilterCriteria *api.SearchFilterType
		}
		// UpdateWorksheet holds details about calls to the UpdateWorksheet method.
		UpdateWorksheet []struct {
			// Cfg is the cfg argument value.
			Cfg *api.Worksheet
		}
	}
}

// CreateWorksheet calls CreateWorksheetFunc.
func (mock *CircAPIMock) CreateWorksheet(cfg *api.Worksheet) (*api.Worksheet, error) {
	if mock.CreateWorksheetFunc == nil {
		panic("moq: CircAPIMock.CreateWorksheetFunc is nil but CircAPI.CreateWorksheet was just called")
	}
	callInfo := struct {
		Cfg *api.Worksheet
	}{
		Cfg: cfg,
	}
	lockCircAPIMockCreateWorksheet.Lock()
	mock.calls.CreateWorksheet = append(mock.calls.CreateWorksheet, callInfo)
	lockCircAPIMockCreateWorksheet.Unlock()
	return mock.CreateWorksheetFunc(cfg)
}

// CreateWorksheetCalls gets all the calls that were made to CreateWorksheet.
// Check the length with:
//     len(mockedCircAPI.CreateWorksheetCalls())
func (mock *CircAPIMock) CreateWorksheetCalls() []struct {
	Cfg *api.Worksheet
} {
	var calls []struct {
		Cfg *api.Worksheet
	}
	lockCircAPIMockCreateWorksheet.RLock()
	calls = mock.calls.CreateWorksheet
	lockCircAPIMockCreateWorksheet.RUnlock()
	return calls
}

// DeleteWorksheetByCID calls DeleteWorksheetByCIDFunc.
func (mock *CircAPIMock) DeleteWorksheetByCID(cid api.CIDType) (bool, error) {
	if mock.DeleteWorksheetByCIDFunc == nil {
		panic("moq: CircAPIMock.DeleteWorksheetByCIDFunc is nil but CircAPI.DeleteWorksheetByCID was just called")
	}
	callInfo := struct {
		Cid api.CIDType
	}{
		Cid: cid,
	}
	lockCircAPIMockDeleteWorksheetByCID.Lock()
	mock.calls.DeleteWorksheetByCID = append(mock.calls.DeleteWorksheetByCID, callInfo)
	lockCircAPIMockDeleteWorksheetByCID.Unlock()
	return mock.DeleteWorksheetByCIDFunc(cid)
}

// DeleteWorksheetByCIDCalls gets all the calls that were made to DeleteWorksheetByCID.
// Check the length with:
//     len(mockedCircAPI.DeleteWorksheetByCIDCalls())
func (mock *CircAPIMock) DeleteWorksheetByCIDCalls() []struct {
	Cid api.CIDType
} {
	var calls []struct {
		Cid api.CIDType
	}
	lockCircAPIMockDeleteWorksheetByCID.RLock()
	calls = mock.calls.DeleteWorksheetByCID
	lockCircAPIMockDeleteWorksheetByCID.RUnlock()
	return calls
}

// FetchWorksheet calls FetchWorksheetFunc.
func (mock *CircAPIMock) FetchWorksheet(cid api.CIDType) (*api.Worksheet, error) {
	if mock.FetchWorksheetFunc == nil {
		panic("moq: CircAPIMock.FetchWorksheetFunc is nil but CircAPI.FetchWorksheet was just called")
	}
	callInfo := struct {
		Cid api.CIDType
	}{
		Cid: cid,
	}
	lockCircAPIMockFetchWorksheet.Lock()
	mock.calls.FetchWorksheet = append(mock.calls.FetchWorksheet, callInfo)
	lockCircAPIMockFetchWorksheet.Unlock()
	return mock.FetchWorksheetFunc(cid)
}

// FetchWorksheetCalls gets all the calls that were made to FetchWorksheet.
// Check the length with:
//     len(mockedCircAPI.FetchWorksheetCalls())
func (mock *CircAPIMock) FetchWorksheetCalls() []struct {
	Cid api.CIDType
} {
	var calls []struct {
		Cid api.CIDType
	}
	lockCircAPIMockFetchWorksheet.RLock()
	calls = mock.calls.FetchWorksheet
	lockCircAPIMockFetchWorksheet.RUnlock()
	return calls
}

// SearchWorksheets calls SearchWorksheetsFunc.
func (mock *CircAPIMock) SearchWorksheets(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Worksheet, error) {
	if mock.SearchWorksheetsFunc == nil {
		panic("moq: CircAPIMock.SearchWorksheetsFunc is nil but CircAPI.SearchWorksheets was just called")
	}
	callInfo := struct {
		SearchCriteria *api.SearchQueryType
		FilterCriteria *api.SearchFilterType
	}{
		SearchCriteria: searchCriteria,
		FilterCriteria: filterCriteria,
	}
	lockCircAPIMockSearchWorksheets.Lock()
	mock.calls.SearchWorksheets = append(mock.calls.SearchWorksheets, callInfo)
	lockCircAPIMockSearchWorksheets.Unlock()
	return mock.SearchWorksheetsFunc(searchCriteria, filterCriteria)
}

// SearchWorksheetsCalls gets all the calls that were made to SearchWorksheets.
// Check the length with:
//     len(mockedCircAPI.SearchWorksheetsCalls())
func (mock *CircAPIMock) SearchWorksheetsCalls() []struct {
	SearchCriteria *api.SearchQueryType
	FilterCriteria *api.SearchFilterType
} {
	var calls []struct {
		SearchCriteria *api.SearchQueryType
		FilterCriteria *api.SearchFilterType
	}
	lockCircAPIMockSearchWorksheets.RLock()
	calls = mock.calls.SearchWorksheets
	lockCircAPIMockSearchWorksheets.RUnlock()
	return calls
}

// UpdateWorksheet calls UpdateWorksheetFunc.
func (mock *CircAPIMock) UpdateWorksheet(cfg *api.Worksheet) (*api.Worksheet, error) {
	if mock.UpdateWorksheetFunc == nil {
		panic("moq: CircAPIMock.UpdateWorksheetFunc is nil but CircAPI.UpdateWorksheet was just called")
	}
	callInfo := struct {
		Cfg *api.Worksheet
	}{
		Cfg: cfg,
	}
	lockCircAPIMockUpdateWorksheet.Lock()
	mock.calls.UpdateWorksheet = append(mock.calls.UpdateWorksheet, callInfo)
	lockCircAPIMockUpdateWorksheet.Unlock()
	return mock.UpdateWorksheetFunc(cfg)
}

// UpdateWorksheetCalls gets all the calls that were made to UpdateWorksheet.
// Check the length with:
//     len(mockedCircAPI.UpdateWorksheetCalls())
func (mock *CircAPIMock) UpdateWorksheetCalls() []struct {
	Cfg *api.Worksheet
} {
	var calls []struct {
		Cfg *api.Worksheet
	}
	lockCircAPIMockUpdateWorksheet.RLock()
	calls = mock.calls.UpdateWorksheet
	lockCircAPIMockUpdateWorksheet.RUnlock()
	return calls
}
