// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package graphs

import (
	"sync"

	circapi "github.com/circonus-labs/go-apiclient"
)

var (
	lockCircAPIMockCreateGraph      sync.RWMutex
	lockCircAPIMockDeleteGraphByCID sync.RWMutex
	lockCircAPIMockFetchGraph       sync.RWMutex
	lockCircAPIMockSearchGraphs     sync.RWMutex
	lockCircAPIMockUpdateGraph      sync.RWMutex
)

// CircAPIMock is a mock implementation of CircAPI.
//
//     func TestSomethingThatUsesCircAPI(t *testing.T) {
//
//         // make and configure a mocked CircAPI
//         mockedCircAPI := &CircAPIMock{
//             CreateGraphFunc: func(cfg *circapi.Graph) (*circapi.Graph, error) {
// 	               panic("TODO: mock out the CreateGraph method")
//             },
//             DeleteGraphByCIDFunc: func(cid circapi.CIDType) (bool, error) {
// 	               panic("TODO: mock out the DeleteGraphByCID method")
//             },
//             FetchGraphFunc: func(cid circapi.CIDType) (*circapi.Graph, error) {
// 	               panic("TODO: mock out the FetchGraph method")
//             },
//             SearchGraphsFunc: func(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Graph, error) {
// 	               panic("TODO: mock out the SearchGraphs method")
//             },
//             UpdateGraphFunc: func(cfg *circapi.Graph) (*circapi.Graph, error) {
// 	               panic("TODO: mock out the UpdateGraph method")
//             },
//         }
//
//         // TODO: use mockedCircAPI in code that requires CircAPI
//         //       and then make assertions.
//
//     }
type CircAPIMock struct {
	// CreateGraphFunc mocks the CreateGraph method.
	CreateGraphFunc func(cfg *circapi.Graph) (*circapi.Graph, error)

	// DeleteGraphByCIDFunc mocks the DeleteGraphByCID method.
	DeleteGraphByCIDFunc func(cid circapi.CIDType) (bool, error)

	// FetchGraphFunc mocks the FetchGraph method.
	FetchGraphFunc func(cid circapi.CIDType) (*circapi.Graph, error)

	// SearchGraphsFunc mocks the SearchGraphs method.
	SearchGraphsFunc func(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Graph, error)

	// UpdateGraphFunc mocks the UpdateGraph method.
	UpdateGraphFunc func(cfg *circapi.Graph) (*circapi.Graph, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateGraph holds details about calls to the CreateGraph method.
		CreateGraph []struct {
			// Cfg is the cfg argument value.
			Cfg *circapi.Graph
		}
		// DeleteGraphByCID holds details about calls to the DeleteGraphByCID method.
		DeleteGraphByCID []struct {
			// Cid is the cid argument value.
			Cid circapi.CIDType
		}
		// FetchGraph holds details about calls to the FetchGraph method.
		FetchGraph []struct {
			// Cid is the cid argument value.
			Cid circapi.CIDType
		}
		// SearchGraphs holds details about calls to the SearchGraphs method.
		SearchGraphs []struct {
			// SearchCriteria is the searchCriteria argument value.
			SearchCriteria *circapi.SearchQueryType
			// FilterCriteria is the filterCriteria argument value.
			FilterCriteria *circapi.SearchFilterType
		}
		// UpdateGraph holds details about calls to the UpdateGraph method.
		UpdateGraph []struct {
			// Cfg is the cfg argument value.
			Cfg *circapi.Graph
		}
	}
}

// CreateGraph calls CreateGraphFunc.
func (mock *CircAPIMock) CreateGraph(cfg *circapi.Graph) (*circapi.Graph, error) {
	if mock.CreateGraphFunc == nil {
		panic("moq: CircAPIMock.CreateGraphFunc is nil but CircAPI.CreateGraph was just called")
	}
	callInfo := struct {
		Cfg *circapi.Graph
	}{
		Cfg: cfg,
	}
	lockCircAPIMockCreateGraph.Lock()
	mock.calls.CreateGraph = append(mock.calls.CreateGraph, callInfo)
	lockCircAPIMockCreateGraph.Unlock()
	return mock.CreateGraphFunc(cfg)
}

// CreateGraphCalls gets all the calls that were made to CreateGraph.
// Check the length with:
//     len(mockedCircAPI.CreateGraphCalls())
func (mock *CircAPIMock) CreateGraphCalls() []struct {
	Cfg *circapi.Graph
} {
	var calls []struct {
		Cfg *circapi.Graph
	}
	lockCircAPIMockCreateGraph.RLock()
	calls = mock.calls.CreateGraph
	lockCircAPIMockCreateGraph.RUnlock()
	return calls
}

// DeleteGraphByCID calls DeleteGraphByCIDFunc.
func (mock *CircAPIMock) DeleteGraphByCID(cid circapi.CIDType) (bool, error) {
	if mock.DeleteGraphByCIDFunc == nil {
		panic("moq: CircAPIMock.DeleteGraphByCIDFunc is nil but CircAPI.DeleteGraphByCID was just called")
	}
	callInfo := struct {
		Cid circapi.CIDType
	}{
		Cid: cid,
	}
	lockCircAPIMockDeleteGraphByCID.Lock()
	mock.calls.DeleteGraphByCID = append(mock.calls.DeleteGraphByCID, callInfo)
	lockCircAPIMockDeleteGraphByCID.Unlock()
	return mock.DeleteGraphByCIDFunc(cid)
}

// DeleteGraphByCIDCalls gets all the calls that were made to DeleteGraphByCID.
// Check the length with:
//     len(mockedCircAPI.DeleteGraphByCIDCalls())
func (mock *CircAPIMock) DeleteGraphByCIDCalls() []struct {
	Cid circapi.CIDType
} {
	var calls []struct {
		Cid circapi.CIDType
	}
	lockCircAPIMockDeleteGraphByCID.RLock()
	calls = mock.calls.DeleteGraphByCID
	lockCircAPIMockDeleteGraphByCID.RUnlock()
	return calls
}

// FetchGraph calls FetchGraphFunc.
func (mock *CircAPIMock) FetchGraph(cid circapi.CIDType) (*circapi.Graph, error) {
	if mock.FetchGraphFunc == nil {
		panic("moq: CircAPIMock.FetchGraphFunc is nil but CircAPI.FetchGraph was just called")
	}
	callInfo := struct {
		Cid circapi.CIDType
	}{
		Cid: cid,
	}
	lockCircAPIMockFetchGraph.Lock()
	mock.calls.FetchGraph = append(mock.calls.FetchGraph, callInfo)
	lockCircAPIMockFetchGraph.Unlock()
	return mock.FetchGraphFunc(cid)
}

// FetchGraphCalls gets all the calls that were made to FetchGraph.
// Check the length with:
//     len(mockedCircAPI.FetchGraphCalls())
func (mock *CircAPIMock) FetchGraphCalls() []struct {
	Cid circapi.CIDType
} {
	var calls []struct {
		Cid circapi.CIDType
	}
	lockCircAPIMockFetchGraph.RLock()
	calls = mock.calls.FetchGraph
	lockCircAPIMockFetchGraph.RUnlock()
	return calls
}

// SearchGraphs calls SearchGraphsFunc.
func (mock *CircAPIMock) SearchGraphs(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Graph, error) {
	if mock.SearchGraphsFunc == nil {
		panic("moq: CircAPIMock.SearchGraphsFunc is nil but CircAPI.SearchGraphs was just called")
	}
	callInfo := struct {
		SearchCriteria *circapi.SearchQueryType
		FilterCriteria *circapi.SearchFilterType
	}{
		SearchCriteria: searchCriteria,
		FilterCriteria: filterCriteria,
	}
	lockCircAPIMockSearchGraphs.Lock()
	mock.calls.SearchGraphs = append(mock.calls.SearchGraphs, callInfo)
	lockCircAPIMockSearchGraphs.Unlock()
	return mock.SearchGraphsFunc(searchCriteria, filterCriteria)
}

// SearchGraphsCalls gets all the calls that were made to SearchGraphs.
// Check the length with:
//     len(mockedCircAPI.SearchGraphsCalls())
func (mock *CircAPIMock) SearchGraphsCalls() []struct {
	SearchCriteria *circapi.SearchQueryType
	FilterCriteria *circapi.SearchFilterType
} {
	var calls []struct {
		SearchCriteria *circapi.SearchQueryType
		FilterCriteria *circapi.SearchFilterType
	}
	lockCircAPIMockSearchGraphs.RLock()
	calls = mock.calls.SearchGraphs
	lockCircAPIMockSearchGraphs.RUnlock()
	return calls
}

// UpdateGraph calls UpdateGraphFunc.
func (mock *CircAPIMock) UpdateGraph(cfg *circapi.Graph) (*circapi.Graph, error) {
	if mock.UpdateGraphFunc == nil {
		panic("moq: CircAPIMock.UpdateGraphFunc is nil but CircAPI.UpdateGraph was just called")
	}
	callInfo := struct {
		Cfg *circapi.Graph
	}{
		Cfg: cfg,
	}
	lockCircAPIMockUpdateGraph.Lock()
	mock.calls.UpdateGraph = append(mock.calls.UpdateGraph, callInfo)
	lockCircAPIMockUpdateGraph.Unlock()
	return mock.UpdateGraphFunc(cfg)
}

// UpdateGraphCalls gets all the calls that were made to UpdateGraph.
// Check the length with:
//     len(mockedCircAPI.UpdateGraphCalls())
func (mock *CircAPIMock) UpdateGraphCalls() []struct {
	Cfg *circapi.Graph
} {
	var calls []struct {
		Cfg *circapi.Graph
	}
	lockCircAPIMockUpdateGraph.RLock()
	calls = mock.calls.UpdateGraph
	lockCircAPIMockUpdateGraph.RUnlock()
	return calls
}
