// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package dashboard

import (
	"github.com/circonus-labs/circonus-gometrics/api"
	"sync"
)

var (
	lockAPIMockCreateDashboard      sync.RWMutex
	lockAPIMockDeleteDashboardByCID sync.RWMutex
	lockAPIMockFetchDashboard       sync.RWMutex
	lockAPIMockSearchDashboards     sync.RWMutex
	lockAPIMockUpdateDashboard      sync.RWMutex
)

// APIMock is a mock implementation of API.
//
//     func TestSomethingThatUsesAPI(t *testing.T) {
//
//         // make and configure a mocked API
//         mockedAPI := &APIMock{
//             CreateDashboardFunc: func(cfg *api.Dashboard) (*api.Dashboard, error) {
// 	               panic("TODO: mock out the CreateDashboard method")
//             },
//             DeleteDashboardByCIDFunc: func(cid api.CIDType) (bool, error) {
// 	               panic("TODO: mock out the DeleteDashboardByCID method")
//             },
//             FetchDashboardFunc: func(cid api.CIDType) (*api.Dashboard, error) {
// 	               panic("TODO: mock out the FetchDashboard method")
//             },
//             SearchDashboardsFunc: func(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Dashboard, error) {
// 	               panic("TODO: mock out the SearchDashboards method")
//             },
//             UpdateDashboardFunc: func(cfg *api.Dashboard) (*api.Dashboard, error) {
// 	               panic("TODO: mock out the UpdateDashboard method")
//             },
//         }
//
//         // TODO: use mockedAPI in code that requires API
//         //       and then make assertions.
//
//     }
type APIMock struct {
	// CreateDashboardFunc mocks the CreateDashboard method.
	CreateDashboardFunc func(cfg *api.Dashboard) (*api.Dashboard, error)

	// DeleteDashboardByCIDFunc mocks the DeleteDashboardByCID method.
	DeleteDashboardByCIDFunc func(cid api.CIDType) (bool, error)

	// FetchDashboardFunc mocks the FetchDashboard method.
	FetchDashboardFunc func(cid api.CIDType) (*api.Dashboard, error)

	// SearchDashboardsFunc mocks the SearchDashboards method.
	SearchDashboardsFunc func(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Dashboard, error)

	// UpdateDashboardFunc mocks the UpdateDashboard method.
	UpdateDashboardFunc func(cfg *api.Dashboard) (*api.Dashboard, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateDashboard holds details about calls to the CreateDashboard method.
		CreateDashboard []struct {
			// Cfg is the cfg argument value.
			Cfg *api.Dashboard
		}
		// DeleteDashboardByCID holds details about calls to the DeleteDashboardByCID method.
		DeleteDashboardByCID []struct {
			// Cid is the cid argument value.
			Cid api.CIDType
		}
		// FetchDashboard holds details about calls to the FetchDashboard method.
		FetchDashboard []struct {
			// Cid is the cid argument value.
			Cid api.CIDType
		}
		// SearchDashboards holds details about calls to the SearchDashboards method.
		SearchDashboards []struct {
			// SearchCriteria is the searchCriteria argument value.
			SearchCriteria *api.SearchQueryType
			// FilterCriteria is the filterCriteria argument value.
			FilterCriteria *api.SearchFilterType
		}
		// UpdateDashboard holds details about calls to the UpdateDashboard method.
		UpdateDashboard []struct {
			// Cfg is the cfg argument value.
			Cfg *api.Dashboard
		}
	}
}

// CreateDashboard calls CreateDashboardFunc.
func (mock *APIMock) CreateDashboard(cfg *api.Dashboard) (*api.Dashboard, error) {
	if mock.CreateDashboardFunc == nil {
		panic("moq: APIMock.CreateDashboardFunc is nil but API.CreateDashboard was just called")
	}
	callInfo := struct {
		Cfg *api.Dashboard
	}{
		Cfg: cfg,
	}
	lockAPIMockCreateDashboard.Lock()
	mock.calls.CreateDashboard = append(mock.calls.CreateDashboard, callInfo)
	lockAPIMockCreateDashboard.Unlock()
	return mock.CreateDashboardFunc(cfg)
}

// CreateDashboardCalls gets all the calls that were made to CreateDashboard.
// Check the length with:
//     len(mockedAPI.CreateDashboardCalls())
func (mock *APIMock) CreateDashboardCalls() []struct {
	Cfg *api.Dashboard
} {
	var calls []struct {
		Cfg *api.Dashboard
	}
	lockAPIMockCreateDashboard.RLock()
	calls = mock.calls.CreateDashboard
	lockAPIMockCreateDashboard.RUnlock()
	return calls
}

// DeleteDashboardByCID calls DeleteDashboardByCIDFunc.
func (mock *APIMock) DeleteDashboardByCID(cid api.CIDType) (bool, error) {
	if mock.DeleteDashboardByCIDFunc == nil {
		panic("moq: APIMock.DeleteDashboardByCIDFunc is nil but API.DeleteDashboardByCID was just called")
	}
	callInfo := struct {
		Cid api.CIDType
	}{
		Cid: cid,
	}
	lockAPIMockDeleteDashboardByCID.Lock()
	mock.calls.DeleteDashboardByCID = append(mock.calls.DeleteDashboardByCID, callInfo)
	lockAPIMockDeleteDashboardByCID.Unlock()
	return mock.DeleteDashboardByCIDFunc(cid)
}

// DeleteDashboardByCIDCalls gets all the calls that were made to DeleteDashboardByCID.
// Check the length with:
//     len(mockedAPI.DeleteDashboardByCIDCalls())
func (mock *APIMock) DeleteDashboardByCIDCalls() []struct {
	Cid api.CIDType
} {
	var calls []struct {
		Cid api.CIDType
	}
	lockAPIMockDeleteDashboardByCID.RLock()
	calls = mock.calls.DeleteDashboardByCID
	lockAPIMockDeleteDashboardByCID.RUnlock()
	return calls
}

// FetchDashboard calls FetchDashboardFunc.
func (mock *APIMock) FetchDashboard(cid api.CIDType) (*api.Dashboard, error) {
	if mock.FetchDashboardFunc == nil {
		panic("moq: APIMock.FetchDashboardFunc is nil but API.FetchDashboard was just called")
	}
	callInfo := struct {
		Cid api.CIDType
	}{
		Cid: cid,
	}
	lockAPIMockFetchDashboard.Lock()
	mock.calls.FetchDashboard = append(mock.calls.FetchDashboard, callInfo)
	lockAPIMockFetchDashboard.Unlock()
	return mock.FetchDashboardFunc(cid)
}

// FetchDashboardCalls gets all the calls that were made to FetchDashboard.
// Check the length with:
//     len(mockedAPI.FetchDashboardCalls())
func (mock *APIMock) FetchDashboardCalls() []struct {
	Cid api.CIDType
} {
	var calls []struct {
		Cid api.CIDType
	}
	lockAPIMockFetchDashboard.RLock()
	calls = mock.calls.FetchDashboard
	lockAPIMockFetchDashboard.RUnlock()
	return calls
}

// SearchDashboards calls SearchDashboardsFunc.
func (mock *APIMock) SearchDashboards(searchCriteria *api.SearchQueryType, filterCriteria *api.SearchFilterType) (*[]api.Dashboard, error) {
	if mock.SearchDashboardsFunc == nil {
		panic("moq: APIMock.SearchDashboardsFunc is nil but API.SearchDashboards was just called")
	}
	callInfo := struct {
		SearchCriteria *api.SearchQueryType
		FilterCriteria *api.SearchFilterType
	}{
		SearchCriteria: searchCriteria,
		FilterCriteria: filterCriteria,
	}
	lockAPIMockSearchDashboards.Lock()
	mock.calls.SearchDashboards = append(mock.calls.SearchDashboards, callInfo)
	lockAPIMockSearchDashboards.Unlock()
	return mock.SearchDashboardsFunc(searchCriteria, filterCriteria)
}

// SearchDashboardsCalls gets all the calls that were made to SearchDashboards.
// Check the length with:
//     len(mockedAPI.SearchDashboardsCalls())
func (mock *APIMock) SearchDashboardsCalls() []struct {
	SearchCriteria *api.SearchQueryType
	FilterCriteria *api.SearchFilterType
} {
	var calls []struct {
		SearchCriteria *api.SearchQueryType
		FilterCriteria *api.SearchFilterType
	}
	lockAPIMockSearchDashboards.RLock()
	calls = mock.calls.SearchDashboards
	lockAPIMockSearchDashboards.RUnlock()
	return calls
}

// UpdateDashboard calls UpdateDashboardFunc.
func (mock *APIMock) UpdateDashboard(cfg *api.Dashboard) (*api.Dashboard, error) {
	if mock.UpdateDashboardFunc == nil {
		panic("moq: APIMock.UpdateDashboardFunc is nil but API.UpdateDashboard was just called")
	}
	callInfo := struct {
		Cfg *api.Dashboard
	}{
		Cfg: cfg,
	}
	lockAPIMockUpdateDashboard.Lock()
	mock.calls.UpdateDashboard = append(mock.calls.UpdateDashboard, callInfo)
	lockAPIMockUpdateDashboard.Unlock()
	return mock.UpdateDashboardFunc(cfg)
}

// UpdateDashboardCalls gets all the calls that were made to UpdateDashboard.
// Check the length with:
//     len(mockedAPI.UpdateDashboardCalls())
func (mock *APIMock) UpdateDashboardCalls() []struct {
	Cfg *api.Dashboard
} {
	var calls []struct {
		Cfg *api.Dashboard
	}
	lockAPIMockUpdateDashboard.RLock()
	calls = mock.calls.UpdateDashboard
	lockAPIMockUpdateDashboard.RUnlock()
	return calls
}
