// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package templates

import (
	"sync"

	"github.com/circonus-labs/cosi-server/api"
)

var (
	lockAPIMockFetchTemplate sync.RWMutex
)

// APIMock is a mock implementation of API.
//
//     func TestSomethingThatUsesAPI(t *testing.T) {
//
//         // make and configure a mocked API
//         mockedAPI := &APIMock{
//             FetchTemplateFunc: func(id string) (*api.Template, error) {
// 	               panic("TODO: mock out the FetchTemplate method")
//             },
//         }
//
//         // TODO: use mockedAPI in code that requires API
//         //       and then make assertions.
//
//     }
type APIMock struct {
	// FetchTemplateFunc mocks the FetchTemplate method.
	FetchTemplateFunc func(id string) (*api.Template, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchTemplate holds details about calls to the FetchTemplate method.
		FetchTemplate []struct {
			// ID is the id argument value.
			ID string
		}
	}
}

// FetchTemplate calls FetchTemplateFunc.
func (mock *APIMock) FetchTemplate(id string) (*api.Template, error) {
	if mock.FetchTemplateFunc == nil {
		panic("moq: APIMock.FetchTemplateFunc is nil but API.FetchTemplate was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockAPIMockFetchTemplate.Lock()
	mock.calls.FetchTemplate = append(mock.calls.FetchTemplate, callInfo)
	lockAPIMockFetchTemplate.Unlock()
	return mock.FetchTemplateFunc(id)
}

// FetchTemplateCalls gets all the calls that were made to FetchTemplate.
// Check the length with:
//     len(mockedAPI.FetchTemplateCalls())
func (mock *APIMock) FetchTemplateCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockAPIMockFetchTemplate.RLock()
	calls = mock.calls.FetchTemplate
	lockAPIMockFetchTemplate.RUnlock()
	return calls
}
