// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package worksheet

import (
	"sync"

	circapi "github.com/circonus-labs/go-apiclient"
)

var (
	lockAPIMockCreateWorksheet      sync.RWMutex
	lockAPIMockDeleteWorksheetByCID sync.RWMutex
	lockAPIMockFetchWorksheet       sync.RWMutex
	lockAPIMockSearchWorksheets     sync.RWMutex
	lockAPIMockUpdateWorksheet      sync.RWMutex
)

// APIMock is a mock implementation of API.
//
//     func TestSomethingThatUsesAPI(t *testing.T) {
//
//         // make and configure a mocked API
//         mockedAPI := &APIMock{
//             CreateWorksheetFunc: func(cfg *circapi.Worksheet) (*circapi.Worksheet, error) {
// 	               panic("TODO: mock out the CreateWorksheet method")
//             },
//             DeleteWorksheetByCIDFunc: func(cid circapi.CIDType) (bool, error) {
// 	               panic("TODO: mock out the DeleteWorksheetByCID method")
//             },
//             FetchWorksheetFunc: func(cid circapi.CIDType) (*circapi.Worksheet, error) {
// 	               panic("TODO: mock out the FetchWorksheet method")
//             },
//             SearchWorksheetsFunc: func(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Worksheet, error) {
// 	               panic("TODO: mock out the SearchWorksheets method")
//             },
//             UpdateWorksheetFunc: func(cfg *circapi.Worksheet) (*circapi.Worksheet, error) {
// 	               panic("TODO: mock out the UpdateWorksheet method")
//             },
//         }
//
//         // TODO: use mockedAPI in code that requires API
//         //       and then make assertions.
//
//     }
type APIMock struct {
	// CreateWorksheetFunc mocks the CreateWorksheet method.
	CreateWorksheetFunc func(cfg *circapi.Worksheet) (*circapi.Worksheet, error)

	// DeleteWorksheetByCIDFunc mocks the DeleteWorksheetByCID method.
	DeleteWorksheetByCIDFunc func(cid circapi.CIDType) (bool, error)

	// FetchWorksheetFunc mocks the FetchWorksheet method.
	FetchWorksheetFunc func(cid circapi.CIDType) (*circapi.Worksheet, error)

	// SearchWorksheetsFunc mocks the SearchWorksheets method.
	SearchWorksheetsFunc func(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Worksheet, error)

	// UpdateWorksheetFunc mocks the UpdateWorksheet method.
	UpdateWorksheetFunc func(cfg *circapi.Worksheet) (*circapi.Worksheet, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateWorksheet holds details about calls to the CreateWorksheet method.
		CreateWorksheet []struct {
			// Cfg is the cfg argument value.
			Cfg *circapi.Worksheet
		}
		// DeleteWorksheetByCID holds details about calls to the DeleteWorksheetByCID method.
		DeleteWorksheetByCID []struct {
			// Cid is the cid argument value.
			Cid circapi.CIDType
		}
		// FetchWorksheet holds details about calls to the FetchWorksheet method.
		FetchWorksheet []struct {
			// Cid is the cid argument value.
			Cid circapi.CIDType
		}
		// SearchWorksheets holds details about calls to the SearchWorksheets method.
		SearchWorksheets []struct {
			// SearchCriteria is the searchCriteria argument value.
			SearchCriteria *circapi.SearchQueryType
			// FilterCriteria is the filterCriteria argument value.
			FilterCriteria *circapi.SearchFilterType
		}
		// UpdateWorksheet holds details about calls to the UpdateWorksheet method.
		UpdateWorksheet []struct {
			// Cfg is the cfg argument value.
			Cfg *circapi.Worksheet
		}
	}
}

// CreateWorksheet calls CreateWorksheetFunc.
func (mock *APIMock) CreateWorksheet(cfg *circapi.Worksheet) (*circapi.Worksheet, error) {
	if mock.CreateWorksheetFunc == nil {
		panic("moq: APIMock.CreateWorksheetFunc is nil but API.CreateWorksheet was just called")
	}
	callInfo := struct {
		Cfg *circapi.Worksheet
	}{
		Cfg: cfg,
	}
	lockAPIMockCreateWorksheet.Lock()
	mock.calls.CreateWorksheet = append(mock.calls.CreateWorksheet, callInfo)
	lockAPIMockCreateWorksheet.Unlock()
	return mock.CreateWorksheetFunc(cfg)
}

// CreateWorksheetCalls gets all the calls that were made to CreateWorksheet.
// Check the length with:
//     len(mockedAPI.CreateWorksheetCalls())
func (mock *APIMock) CreateWorksheetCalls() []struct {
	Cfg *circapi.Worksheet
} {
	var calls []struct {
		Cfg *circapi.Worksheet
	}
	lockAPIMockCreateWorksheet.RLock()
	calls = mock.calls.CreateWorksheet
	lockAPIMockCreateWorksheet.RUnlock()
	return calls
}

// DeleteWorksheetByCID calls DeleteWorksheetByCIDFunc.
func (mock *APIMock) DeleteWorksheetByCID(cid circapi.CIDType) (bool, error) {
	if mock.DeleteWorksheetByCIDFunc == nil {
		panic("moq: APIMock.DeleteWorksheetByCIDFunc is nil but API.DeleteWorksheetByCID was just called")
	}
	callInfo := struct {
		Cid circapi.CIDType
	}{
		Cid: cid,
	}
	lockAPIMockDeleteWorksheetByCID.Lock()
	mock.calls.DeleteWorksheetByCID = append(mock.calls.DeleteWorksheetByCID, callInfo)
	lockAPIMockDeleteWorksheetByCID.Unlock()
	return mock.DeleteWorksheetByCIDFunc(cid)
}

// DeleteWorksheetByCIDCalls gets all the calls that were made to DeleteWorksheetByCID.
// Check the length with:
//     len(mockedAPI.DeleteWorksheetByCIDCalls())
func (mock *APIMock) DeleteWorksheetByCIDCalls() []struct {
	Cid circapi.CIDType
} {
	var calls []struct {
		Cid circapi.CIDType
	}
	lockAPIMockDeleteWorksheetByCID.RLock()
	calls = mock.calls.DeleteWorksheetByCID
	lockAPIMockDeleteWorksheetByCID.RUnlock()
	return calls
}

// FetchWorksheet calls FetchWorksheetFunc.
func (mock *APIMock) FetchWorksheet(cid circapi.CIDType) (*circapi.Worksheet, error) {
	if mock.FetchWorksheetFunc == nil {
		panic("moq: APIMock.FetchWorksheetFunc is nil but API.FetchWorksheet was just called")
	}
	callInfo := struct {
		Cid circapi.CIDType
	}{
		Cid: cid,
	}
	lockAPIMockFetchWorksheet.Lock()
	mock.calls.FetchWorksheet = append(mock.calls.FetchWorksheet, callInfo)
	lockAPIMockFetchWorksheet.Unlock()
	return mock.FetchWorksheetFunc(cid)
}

// FetchWorksheetCalls gets all the calls that were made to FetchWorksheet.
// Check the length with:
//     len(mockedAPI.FetchWorksheetCalls())
func (mock *APIMock) FetchWorksheetCalls() []struct {
	Cid circapi.CIDType
} {
	var calls []struct {
		Cid circapi.CIDType
	}
	lockAPIMockFetchWorksheet.RLock()
	calls = mock.calls.FetchWorksheet
	lockAPIMockFetchWorksheet.RUnlock()
	return calls
}

// SearchWorksheets calls SearchWorksheetsFunc.
func (mock *APIMock) SearchWorksheets(searchCriteria *circapi.SearchQueryType, filterCriteria *circapi.SearchFilterType) (*[]circapi.Worksheet, error) {
	if mock.SearchWorksheetsFunc == nil {
		panic("moq: APIMock.SearchWorksheetsFunc is nil but API.SearchWorksheets was just called")
	}
	callInfo := struct {
		SearchCriteria *circapi.SearchQueryType
		FilterCriteria *circapi.SearchFilterType
	}{
		SearchCriteria: searchCriteria,
		FilterCriteria: filterCriteria,
	}
	lockAPIMockSearchWorksheets.Lock()
	mock.calls.SearchWorksheets = append(mock.calls.SearchWorksheets, callInfo)
	lockAPIMockSearchWorksheets.Unlock()
	return mock.SearchWorksheetsFunc(searchCriteria, filterCriteria)
}

// SearchWorksheetsCalls gets all the calls that were made to SearchWorksheets.
// Check the length with:
//     len(mockedAPI.SearchWorksheetsCalls())
func (mock *APIMock) SearchWorksheetsCalls() []struct {
	SearchCriteria *circapi.SearchQueryType
	FilterCriteria *circapi.SearchFilterType
} {
	var calls []struct {
		SearchCriteria *circapi.SearchQueryType
		FilterCriteria *circapi.SearchFilterType
	}
	lockAPIMockSearchWorksheets.RLock()
	calls = mock.calls.SearchWorksheets
	lockAPIMockSearchWorksheets.RUnlock()
	return calls
}

// UpdateWorksheet calls UpdateWorksheetFunc.
func (mock *APIMock) UpdateWorksheet(cfg *circapi.Worksheet) (*circapi.Worksheet, error) {
	if mock.UpdateWorksheetFunc == nil {
		panic("moq: APIMock.UpdateWorksheetFunc is nil but API.UpdateWorksheet was just called")
	}
	callInfo := struct {
		Cfg *circapi.Worksheet
	}{
		Cfg: cfg,
	}
	lockAPIMockUpdateWorksheet.Lock()
	mock.calls.UpdateWorksheet = append(mock.calls.UpdateWorksheet, callInfo)
	lockAPIMockUpdateWorksheet.Unlock()
	return mock.UpdateWorksheetFunc(cfg)
}

// UpdateWorksheetCalls gets all the calls that were made to UpdateWorksheet.
// Check the length with:
//     len(mockedAPI.UpdateWorksheetCalls())
func (mock *APIMock) UpdateWorksheetCalls() []struct {
	Cfg *circapi.Worksheet
} {
	var calls []struct {
		Cfg *circapi.Worksheet
	}
	lockAPIMockUpdateWorksheet.RLock()
	calls = mock.calls.UpdateWorksheet
	lockAPIMockUpdateWorksheet.RUnlock()
	return calls
}
